# Generated by Django 4.1.13 on 2026-04-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='group_members',
            field=models.PositiveIntegerField(help_text='Number of members in group'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.CharField(choices=[('00:00-01:00', '12:00 AM – 1:00 AM'), ('01:00-02:00', '1:00 AM – 2:00 AM'), ('02:00-03:00', '2:00 AM – 3:00 AM'), ('03:00-04:00', '3:00 AM – 4:00 AM'), ('04:00-05:00', '4:00 AM – 5:00 AM'), ('05:00-06:00', '5:00 AM – 6:00 AM'), ('06:00-07:00', '6:00 AM – 7:00 AM'), ('07:00-08:00', '7:00 AM – 8:00 AM'), ('08:00-09:00', '8:00 AM – 9:00 AM'), ('09:00-10:00', '9:00 AM – 10:00 AM'), ('10:00-11:00', '10:00 AM – 11:00 AM'), ('11:00-12:00', '11:00 AM – 12:00 PM'), ('12:00-13:00', '12:00 PM – 1:00 PM'), ('13:00-14:00', '1:00 PM – 2:00 PM'), ('14:00-15:00', '2:00 PM – 3:00 PM'), ('15:00-16:00', '3:00 PM – 4:00 PM'), ('16:00-17:00', '4:00 PM – 5:00 PM'), ('17:00-18:00', '5:00 PM – 6:00 PM'), ('18:00-19:00', '6:00 PM – 7:00 PM'), ('19:00-20:00', '7:00 PM – 8:00 PM'), ('20:00-21:00', '8:00 PM – 9:00 PM'), ('21:00-22:00', '9:00 PM – 10:00 PM'), ('22:00-23:00', '10:00 PM – 11:00 PM'), ('23:00-00:00', '11:00 PM – 12:00 AM')], max_length=20),
        ),
    ]
